import Burger from "@/components/Burger"
import Head from "next/head"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header id="header-style">
                <div></div>

                <div id="h1-div">
                    <h1>First website header!!!</h1>
                </div>

                <div id="burger-div">
                    <Burger></Burger>
                </div>
            </header>

            <main className="main-container"></main>
        </>
    )
}
