import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-container">
       <h2>
        hello world
        </h2>

      <h3>
      hello again
      </h3>

      <h5>
      hello again x2
      </h5>

      </main>
    </>
  )
}
